######################################################################
# Automatically generated by qmake (2.01a) ven. sept. 24 17:57:13 2010
######################################################################

TEMPLATE = lib
CONFIG += plugin 
TARGET = TT_OpenExrLoader
DESTDIR = ../../../Loaders

linux {
  LIBS += -lIlmImf
  INCLUDEPATH += /usr/include/OpenEXR
}

windows {
  QMAKE_POST_LINK += $$QMAKE_COPY $$quote($$TARGET.pdb) $$quote($$DESTDIR)
  CONFIG(debug, debug|release) {
    LIBS += ../../../Dependencies/Win32/OpenEXR/lib/Debug/Half.lib \
            ../../../Dependencies/Win32/OpenEXR/lib/Debug/Iex.lib \
		    ../../../Dependencies/Win32/OpenEXR/lib/Debug/IlmImf.lib \
            ../../../Dependencies/Win32/OpenEXR/lib/Debug/IlmThread.lib \
		    ../../../Dependencies/Win32/OpenEXR/lib/Debug/Imath.lib \
		    ../../../Dependencies/Win32/OpenEXR/lib/Debug/zlib1.lib
  } else {
    LIBS += ../../../Dependencies/Win32/OpenEXR/lib/Release/Half.lib \
            ../../../Dependencies/Win32/OpenEXR/lib/Release/Iex.lib \
		    ../../../Dependencies/Win32/OpenEXR/lib/Release/IlmImf.lib \
            ../../../Dependencies/Win32/OpenEXR/lib/Release/IlmThread.lib \
		    ../../../Dependencies/Win32/OpenEXR/lib/Release/Imath.lib \
		    ../../../Dependencies/Win32/OpenEXR/lib/Release/zlib1.lib
  }
  LIBS += ../../../TT_Api.lib
  INCLUDEPATH += ../../../Dependencies/Win32/OpenEXR/include/OpenEXR
}


DEPENDPATH += . 
INCLUDEPATH += . ../.. ../../Api ../../../ETW

# Input
HEADERS += OpenExrLoader.h
SOURCES += OpenExrLoader.cpp
