######################################################################
# Automatically generated by qmake (2.01a) ven. sept. 24 17:57:13 2010
######################################################################

TEMPLATE = lib
CONFIG += plugin
TARGET = TT_LdrFormatsLoader
DESTDIR = ../../../Loaders

windows {
  LIBS += ../../../TT_Api.lib
}

DEPENDPATH += . 
INCLUDEPATH += . ../.. ../../Api

# Input
HEADERS += LdrFormatsLoader.h
SOURCES += LdrFormatsLoader.cpp
